name: "🐞 Bug Report"
description: "Report unexpected behaviour or errors in Gradient Generator"
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is and how to reproduce it.

  - type: input
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please list the steps that trigger the bug.
      placeholder: |
        1. Go to “...”
        2. Click on “...”
        3. See unexpected behavior

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?

  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
      description: What actually happened?

  - type: input
    id: raycast-version
    attributes:
      label: Raycast version
      description: Version of Raycast installed.

  - type: input
    id: os-version
    attributes:
      label: macOS version
      description: E.g., macOS 14.4

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other information, logs, or screenshots that could help.
