name: "✨ Feature Request"
description: "Suggest a new feature or enhancement for Gradient Generator"
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Is your feature request related to a problem? Please describe.**
        For example, “I’d like to…”, or “I’m struggling with…”

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution or workflow
      description: Describe the idea in detail.
      placeholder: A clear and concise description of what you want to happen.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you considered
      description: Any alternative solutions or features you considered.

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: How would this feature improve your workflow?

  - type: input
    id: additional-context
    attributes:
      label: Additional context
      description: Any extra context, mockups, or examples.
