name: "📝 General Issue"
description: "Use this for questions or general discussion"
title: "[ISSUE] "
labels: ["discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe your question or topic. Be as detailed as possible.

  - type: input
    id: context
    attributes:
      label: Context or background
      description: Optional details that might be helpful.

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Any extra details to clarify or support your issue.
