name: "Bug Report"
description: "File a bug report to help us improve the extension"
title: "bug: <short description>"
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug. Please fill out as much as you can.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you do, what did you expect to happen, and what actually happened?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Be precise and include example inputs or sample gradients if relevant.
      placeholder: |
        1. Open Raycast → Gradient Generator
        2. Click …
        3. Observe …
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or recordings
      description: Drag-and-drop images or videos that show the issue.
    validations:
      required: false

  - type: input
    id: raycast-version
    attributes:
      label: Raycast version
      placeholder: e.g. 1.77.0
    validations:
      required: true

  - type: input
    id: macos-version
    attributes:
      label: macOS version
      placeholder: e.g. 14.5 (Sonoma)
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension version
      placeholder: e.g. 1.0.0
    validations:
      required: true

  - type: dropdown
    id: icon-source
    attributes:
      label: Preference – Icon Source
      options:
        - raycast
        - builtin
        - custom
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs (if any)
      description: Paste any relevant logs. Please redact sensitive data.
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I am using the latest version of the extension
          required: true
        - label: I searched existing issues and did not find a duplicate
          required: true

