name: "Extension Feature Request"
description: "Request a new capability or improvement in the Raycast extension"
title: "feat: <short description>"
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please provide as much detail as possible.

  - type: dropdown
    id: type
    attributes:
      label: Request type
      options:
        - New command
        - Improve existing command
        - Preferences / Settings
        - Performance
        - UI / UX
        - Developer Experience
        - Other
    validations:
      required: true

  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-liner describing the feature
      placeholder: e.g. Export as PNG
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem does this feature address? Why is it useful?
    validations:
      required: false

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the behavior, options, and user flow. Include examples.
      placeholder: |
        - Add a preference "Enable PNG export"
        - In Preview, allow exporting as PNG
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches or prior art
    validations:
      required: false

  - type: checkboxes
    id: scope
    attributes:
      label: Scope (select all that apply)
      options:
        - label: Create Gradient
        - label: Preview Gradient
        - label: Random Gradient
        - label: Saved Gradients
        - label: Gradient Helpers / Outputs (CSS, SwiftUI, Tailwind)
        - label: Preferences / Settings
        - label: Other

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet points that define "done"
      placeholder: |
        - PNG export is available in Preview
        - Tailwind output includes PNG export
        - Copy actions are disabled when fewer than 2 stops
    validations:
      required: false

  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking changes
      options:
        - label: This may change existing behavior or preferences
        - label: Migration steps are described below

  - type: textarea
    id: migration
    attributes:
      label: Migration considerations (if any)
      description: Data transitions, preference changes, or user-visible behavior changes
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / mockups
      description: Drag-and-drop images that illustrate the proposal
    validations:
      required: false

  - type: input
    id: raycast-version
    attributes:
      label: Raycast version (optional)
      placeholder: e.g. 1.77.0
    validations:
      required: false

  - type: input
    id: macos-version
    attributes:
      label: macOS version (optional)
      placeholder: e.g. 14.5 (Sonoma)
    validations:
      required: false

  - type: input
    id: extension-version
    attributes:
      label: Extension version (optional)
      placeholder: e.g. 1.0.0
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I searched existing issues and did not find a duplicate
          required: true
        - label: This is within the scope of the extension (not a one-off gradient/design request)
          required: true
        - label: I am willing to contribute a PR for this feature
          required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Links, references, or anything else
    validations:
      required: false

